Gust of Wind:
  description: Choose 1 of your opponent's Benched Pokémon and switch it with his or her Active Pokémon.
Computer Search:
  description: Discard 2 of the other cards from your hand in order to search your deck for any card and put it into your hand. Shuffle your deck afterward.
Scoop Up:
  description: Choose 1 of your Pokémon in play and return its Basic Pokémon card to your hand. (Discard all cards attached to that card.)
Defender:
  description: Attach Defender to 1 of your Pokémon. At the end of your opponent's next turn, discard Defender. Damage done to that Pokémon by attacks is reduced by 20 (after applying Weakness and Resistance).
PlusPower:
  description: Attach PlusPower to your Active Pokémon. At the end of your turn, discard PlusPower. If this Pokémon's attack does damage to the Defending Pokémon (after applying Weakness and Resistance), the attack does 10 more damage to the Defending Pokémon.
Professor Oak:
  description: Discard your hand, then draw 7 cards.
Bill:
  description: Draw 2 cards.
Energy Removal:
  description: Choose 1 Energy card attached to 1 of your opponent's Pokémon and discard it.
Switch:
  description: Switch 1 of your Benched Pokémon with your Active Pokémon.
Item Finder:
  description: Discard 2 of the other cards from your hand in order to put a Trainer card from your discard pile into your hand.
Super Energy Removal:
  description: Discard 1 Energy card attached to 1 of your own Pokémon in order to choose 1 of your opponent's Pokémon and up to 2 Energy cards attached to it. Discard those Energy cards.
