Mr Fuji:
  description: Choose a Pokémon on your Bench. Shuffle it and any cards attached to it into your deck.
Energy Search:
  description: Search your deck for a basic Energy card and put it into your hand. Shuffle your deck afterward.
Gambler:
  description: Shuffle your hand into your deck. Flip a coin. If heads, draw 8 cards. If tails, draw 1 card.
Recycle:
  description: Flip a coin. If heads, put a card in your discard pile on top of your deck.
Mysterious Fossil:
  description: Play Mysterious Fossil as if it were a Basic Pokémon. While in play, Mysterious Fossil counts as a Pokémon (instead of a Trainer card). Mysterious Fossil has no attacks, can't retreat, and can't be Asleep, Confused, Paralyzed, or Poisoned. If Mysterious Fossil is Knocked Out, it doesn't count as a Knocked Out Pokémon. (Discard it anyway.) At any time during your turn before your attack, you may discard Mysterious Fossil from play.